name: GitHub Auto Follow/Unfollow

on:
  schedule:
    - cron: '0 0 * * *'  # Runs the action daily at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  follow-unfollow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js 20.x (Optional)
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Follow/Unfollow Script
      env:
        TOKEN: ${{ secrets.TOKEN }}
        USERNAME: ${{ secrets.USERNAME }}
      run: python follow_unfollow.py
